### ISSUE TITLE
DesignSpaceDocument.checkDefault() fails

### ISSUE THREAD

**Issue by mashabow** [LettError/designSpaceDocument#25]
```py
Python 3.6.1 (default, Jul 19 2017, 13:24:40)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from designSpaceDocument import DesignSpaceDocument
>>> doc = DesignSpaceDocument()
>>> doc.read('testLocalisedNames.designspace')
>>> doc.checkDefault()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mnakamura/.pyenv/versions/dsd-test/lib/python3.6/site-packages/designSpaceDocument/__init__.py", line 1122, in checkDefault
    mutatorBias = biasFromLocations(masterLocations, preferOrigin=False)
  File "/Users/mnakamura/.pyenv/versions/dsd-test/lib/python3.6/site-packages/mutatorMath/objects/location.py", line 652, in biasFromLocations
    locs.sort()
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

**Comment by anthrotype** [comment]
the error occurs in mutatorMath's `biasFromLocation`. It seems like it is being passed a list of regular `dict` objects as locations instead of mutatorMath's `Location` objects that know how to compare themselves (have `__lt__`).

**Comment by LettError** [comment]
It's relatively easy to make Location objects `loc = Location(dictObject)`.
